services:
  - type: web
    name: fuliza-updatess
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn fuliza_updatess.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: PAYHERO_API_URL
        value: 'https://backend.payhero.co.ke/api/v2/payments'
      - key: PAYHERO_CHANNEL_ID
        sync: false
      - key: PAYHERO_API_USERNAME
        sync: false
      - key: PAYHERO_API_PASSWORD
        sync: false
      - key: PAYHERO_CALLBACK_URL
        sync: false
